apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: angularapp
spec:
  replicas: 1
  template:
    metadata:
      labels:
        label-key : label-value  
    spec:
      containers:
        - name: angularapp
          image: acr4Pipeline.azurecr.io/angularapp
          imagePullPolicy: Always
          ports:
          - containerPort: 80
